##############################################################################
# Copyright (c) 2024, Oak Ridge National Laboratory                          #
# All rights reserved.                                                       #
#                                                                            #
# This file is part of RealTwin and is distributed under a GPL               #
# license. For the licensing terms see the LICENSE file in the top-level     #
# directory.                                                                 #
#                                                                            #
# Contact realtwin developer @ realtwin@ornl.gov                             #
##############################################################################

# if true, the demo data will be used for the simulation, use default data: "chattanooga"
# or string of the name of the demo data, we provide a list of demo data ["chattanooga", "chicago", "nyc", "la", "sf", "dc"]
# For Dev, extend to retrieve the data from the db server.
demo_data: false


input_dir: C:\Users\xh8\ornl_work\github_workspace\Real-Twin-Dev\datasets\chattanooga
output_dir:  # optional

# Absolute and Concrete Scenario Generation
Network:
    NetworkName: chatt  # the name of the network should not have space between words
    NetworkVertices: (-85.14977588011192, 35.040346288414916), (-85.15823020212477, 35.04345144844759), (-85.15829457513502, 35.043293338482925), (-85.14986171079225, 35.04018378032611)
    Net_BBox:  # optional
    ElevationMap: chatt_elev.tif  # optional
Traffic:
    Volume: GridSmart_demand.csv
    TurningRatio: GridSmart_demand.csv
    GridSmart_lookup: GridSmart_lookuptable.csv
Control:
    Signal: Synchro_signal.csv
    Synchro_lookup: Synchro_lookuptable.csv

# Turn, inFlow and Behavior Calibration
Calibration:
    # overall configuration for the calibration
    scenario_config:
        sim_start_time: 28800  # 8:00 AM In seconds
        sim_end_time: 32400  # 9:00 AM In seconds
        calibration_target:
            GEH: 5  # https://en.wikipedia.org/wiki/GEH_statistic
            GEHPercent: 0.85  # accepted match
        calibration_interval: 60  # mins
        demand_interval: 15  # mins

        # input files for the calibration
        path_turn: "turn.xlsx"
        path_inflow: "inflow.xlsx"
        path_summary: "summary.xlsx"
        path_updated_signal: "updated_signal.xml"
        path_Edge_add: "Edge.add.xml"
        path_EdgeData: "EdgeData.xml"   # the EdgeData.xml is generated by the simulation

    turn_inflow:
        initial_params: [0.5, 0.5, 0.5, 0.5, 0.5,
                         0.5, 0.5, 0.5, 0.5, 0.5,
                         0.5, 0.5, 100, 100, 100, 100]
        params_ranges: [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1],
                        [0, 1], [0, 1], [0, 1], [0, 1], [0, 1],
                        [0, 1], [0, 1], [50, 200], [50, 200], [50, 200], [50, 200]]

        # Termination criteria
        max_epoch: 1000  # max number of iterations
        max_fe: 10000  # max number of function evaluations
        max_time: 3600  # max time in seconds
        max_early_stop: 20  # max number of early stop iterations

        ga_config:  # generic algorithm configuration
            # the original configuration for the Genetic Algorithm
            num_generations: 10
            num_variables: 16
            num_turning_ratio: 12  # remaining should be inflow
            ubc: 200  # upper bound of inflow
            population_size: 2  # population size must be even
            crossover_rate: 0.75
            mutation_rate: 0.1
            elitism_size: 1  # number of elite individuals to carry over
            best_fitness_value: 999999  # Large Num, avoid inf
            max_no_improvement: 5  # stop if no improvement in this iteration

            # new configuration for the Genetic Algorithm
            epoch: 1000  # number of generations
            pop_size: 30  # population size
            pc: 0.75  # crossover probability
            pm: 0.1  # mutation probability
            selection: "roulette"  # Options: roulette, tournament, random
            key_way: 0.2  # key way for tournament selection
            crossover: "uniform"  # Options: uniform, one_point, multi_point, arithmetic
            mutation: "swap"  # Options: swap, flip
            elite_best: 0.1  # percentage of the best in elite group, or int, the number of best elite
            elite_worst: 0.3  # percentage of the worst in elite group, or int, the number of worst elite
            model_selection: "BaseGA"  #  BaseGA, EliteSingleGA, EliteMultiGA, MultiGA, SingleGA

        sa_config:  # simulated annealing configuration
            # the original configuration for the Simulated Annealing
            num_variables: 16
            num_turning_ratio: 12  # remaining should be inflow
            initial_temperature: 100
            ubc: 200  # upper bound of inflow
            cost_difference: 2
            accept_prob: 0.5
            stopping_temperature: 0.001

            # new configuration for the Simulated Annealing
            epoch: 1000  # number of generations
            temp_init: 100  # initial temperature
            cooling_rate: 0.891  # same as previous
            scale: 0.1  # scale for the temperature
            model_selection: "OriginalSA"  # OriginalSA, GaussianSA, SwarmSA

        ts_config:  # tabu search configuration
            # the original configuration for the Tabu Search
            iterations: 3
            # tabu_size: 120
            neighborhood_size: 32
            move_range: 0.5   # initial move range
            num_turning_ratio: 12
            max_no_improvement_local: 5
            max_no_improvement_global: 30
            lower_bound: 0
            upper_bound: 1
            lbc: 0  # lower bound for inflow counts
            ubc: 200  # upper bound for inflow counts

            # new configuration for the Tabu Search
            epoch: 1000  # number of generations
            tabu_size: 10  # size of the tabu list;
            neighbour_size: 10  # size of the neighbourhood for generating candidate solutions
            perturbation_scale: 0.05  # scale of perturbation for the solution

    behavior:
        # behavior calibration shared by all algorithms
        EB_tt: 240  # mins?
        WB_tt: 180  # mins?
        EB_edge_list: ["-312", "-293", "-297", "-288", "-286",
                        "-302", "-3221", "-322", "-313", "-284",
                        "-328", "-304"]
        WB_edge_list: ["-2801", "-280", "-307", "-327", "-281",
                        "-315", "-321", "-300", "-2851", "-285",
                        "-290", "-298", "-295"]
        initial_params:
            min_gap: 2.5  # min gap between vehicles in meters
            acceleration: 2.6  #  max acceleration in m/s^2
            deceleration: 4.5  # max deceleration in m/s^2
            sigma: 0.5  # driver imperfection
            tau: 1.00  # desired headway
            emergencyDecel: 9.0  # emergency deceleration in m/s^2
        params_ranges:
            min_gap: [1.0, 3.0]
            acceleration: [2.5, 3.0]
            deceleration: [4.0, 5.3]
            sigma: [0.0, 1.0]
            tau: [0.25, 1.25]
            emergencyDecel: [5.0, 9.3]

        # Termination criteria
        max_epoch: 1000  # max number of iterations
        max_fe: 10000  # max number of function evaluations
        max_time: 3600  # max time in seconds
        max_early_stop: 20  # max number of early stop iterations

        ga_config:
            epoch: 1000  # number of generations
            pop_size: 30  # population size
            pc: 0.75  # crossover probability
            pm: 0.1  # mutation probability

            selection: "roulette"  # Options: roulette, tournament, random
            key_way: 0.2  # key way for tournament selection
            crossover: "uniform"  # Options: uniform, one_point, multi_point, arithmetic
            mutation: "swap"  # Options: swap, flip
            elite_best: 0.1  # percentage of the best in elite group, or int, the number of best elite
            elite_worst: 0.3  # percentage of the worst in elite group, or int, the number of worst elite
            model_selection: "BaseGA"  #  BaseGA, EliteSingleGA, EliteMultiGA, MultiGA, SingleGA

        sa_config:
            epoch: 1000  # number of generations
            temp_init: 100  # initial temperature
            cooling_rate: 0.891  # same as previous
            scale: 0.1  # scale for the temperature
            model_selection: "OriginalSA"  # OriginalSA, GaussianSA, SwarmSA

        ts_config:
            # the original configuration for the Tabu Search
            max_iteration: 50
            num_neighbors: 5
            tabu_list_size: 10
            decimal_places: 5

            # the new configuration for the Tabu Search
            epoch: 1000  # number of generations
            tabu_size: 10  # size of the tabu list; same as previous value
            neighbour_size: 10  # size of the neighbourhood for generating candidate solutions
            perturbation_scale: 0.05  # scale of perturbation for the solution
